-- Clean the database
TRUNCATE TABLE EMPRUNTER
DELETE FROM ABONN�S


-- Variable declaration
DECLARE @marc AS int
DECLARE @nopal�on AS int


-- Marc Antoine (marc, antoine)
INSERT INTO ABONN�S (CODE_PAYS, NOM_ABONN�, PR�NOM_ABONN�, LOGIN_ABONN�, PASSWORD_ABONN�)
VALUES (2, 'Antoine', 'Marc', 'marc', 'antoine')

-- Napol�on Bonnaparte (napol�on bonnaparte)
INSERT INTO ABONN�S (CODE_PAYS, NOM_ABONN�, PR�NOM_ABONN�, LOGIN_ABONN�, PASSWORD_ABONN�)
VALUES (1, 'Bonnaparte', 'Napol�on', 'napol�on', 'bonnaparte')


-- Variable initialization
SELECT @marc = CODE_ABONN� FROM ABONN�S WHERE LOGIN_ABONN� = 'marc'
SELECT @nopal�on = CODE_ABONN� FROM ABONN�S WHERE LOGIN_ABONN� = 'napol�on'


-- Loan late by 11 days
INSERT INTO EMPRUNTER (CODE_ABONN�, CODE_ALBUM, DATE_EMPRUNT, DATE_RETOUR_ATTENDUE)
VALUES (@nopal�on, 1, DATEADD(MM, -1, GETDATE()), DATEADD(DD, -11, GETDATE()))

-- Loan late by 8 days (not displayed)
INSERT INTO EMPRUNTER (CODE_ABONN�, CODE_ALBUM, DATE_EMPRUNT, DATE_RETOUR_ATTENDUE)
VALUES (@nopal�on, 2, DATEADD(MM, -1, GETDATE()), DATEADD(DD, -8, GETDATE()))

-- Loan late by 30 days
INSERT INTO EMPRUNTER (CODE_ABONN�, CODE_ALBUM, DATE_EMPRUNT, DATE_RETOUR_ATTENDUE)
VALUES (@marc, 3, DATEADD(MM, -2, GETDATE()), DATEADD(DD, -30, GETDATE()))

-- Extended loan
INSERT INTO EMPRUNTER (CODE_ABONN�, CODE_ALBUM, DATE_EMPRUNT, DATE_RETOUR_ATTENDUE)
VALUES (@marc, 4, GETDATE(), DATEADD(MM, 2, GETDATE()))

-- Extended loan
INSERT INTO EMPRUNTER (CODE_ABONN�, CODE_ALBUM, DATE_EMPRUNT, DATE_RETOUR_ATTENDUE)
VALUES (@nopal�on, 5, GETDATE(), DATEADD(MM, 5, GETDATE()))

-- Regular loan
INSERT INTO EMPRUNTER (CODE_ABONN�, CODE_ALBUM, DATE_EMPRUNT, DATE_RETOUR_ATTENDUE)
VALUES (@marc, 6, GETDATE(), DATEADD(DD, 2, GETDATE()))


-- Loan display
SELECT * FROM EMPRUNTER